wiki_credentials:
  username: "username"
  password: "password"

wiki_settings:
  api_url: "https://wiki.yoursite.org/api.php"
  index_page: "CNC/tools"
  page_prefix: "tool"
  publish: false

gui_settings:
  default_window_size: "1559x780"
  theme: "Fusion"

file_paths:
  base_directory: "FreeCAD"
  qr_images_location: "qrImages"
  bit_images: "BitImages"
  database_path: "tools.db"
  master_tool_table: "tool.tbl"

freecad:
  versions: ["v1-0", "v1-1", "v1-2"]
  library_name: "Default.fctl"

machine_settings:
  max_rpm: 24000

tool_settings:
  default_shape: "endmill.fcstd"
  fraction_precision: 64
  imperial_precision: 4
  metric_precision: 3
  angle_precision: 4
  fields_to_format:
    SuggestedMaxDOC: "dimension"
    ToolShankSize: "dimension"
    OAL: "dimension"
    LOC: "dimension"
    ToolDiameter: "dimension"
    Chipload: "dimension"
    TipDiameter: "dimension"
    TorusRadius: "dimension"
    ShaftDiameter: "dimension"
    BladeThickness: "dimension"
    CapDiameter: "dimension"
    CapHeight: "dimension"
    CuttingEdgeAngle: "angle"
    TipAngle: "angle"
    ToolMaxRPM: "rpm"
    ToolNumber: "number"
    Flutes: "number"

qr_code_settings:
  base_url: "https://wiki.knoxmakers.org/Nibblerbot/tools/"
  box_size: 10
  border: 2

logging:
  log_file: "openbitlib.log"
  log_level: "DEBUG"

manifest_settings:
  manifest_dir: "../YourCNC"
  manifest_file: ".YourCNC_manifest.json"
